name: Native Build & Test

env:
  cacheId: '4' # increment to expire the cache

on:
  push:
    branches: [main]

jobs:
  # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      # - name: Install fastlane
      #   run: |
      #     gem install fastlane

      # Watch for changes to the `App` and `iOS` paths, use
      # git for cache keys.
      - name: Generate cache key
        run: |
          echo $(git rev-parse HEAD:App) > ./dd-cache-key.txt
          echo $(git rev-parse HEAD:ios) >> ./dd-cache-key.txt

      - name: Cache derived data
        uses: actions/cache@v1
        with:
          path: xbuild/Build
          key: ${{ runner.os }}-dd-xcode-${{ env.cacheId }}-${{ hashFiles('**/dd-cache-key.txt') }}
          restore-keys: |
            ${{ runner.os }}-dd-xcode-${{ env.cacheId }}-

      - name: Build Keychain
        env:
          CERTIFICATE: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        run: |
          scripts/makekc.sh ${{ secrets.KEYCHIAN_PASSWD }}

      - name: Create Provisioning Profile
        env:         
          PROVISIONING_PROFILE: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          scripts/makepp.sh

      # - name: fastlane
      #   env:
      #     FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      #     FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      #     FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
      #   run: |
      #     brew install fastlane && fastlane beta

      - name: Explore z
        run: |
          xcode-select -p && sudo xcode-select -r

      - name: Build
        run: |
          xcodebuild \
          -project TestBuildAndSign.xcodeproj \
          -scheme TestBuildAndSign \
          -configuration Release \
          -derivedDataPath xbuild \
          -xcconfig release.xcconfig \
          -archivePath TestBuildAndSign.xcarchive \
          -sdk iphoneos \
          -verbose \
          archive

      - name: Explore 2
        run: |
          ls -lah

      - name: Archive & Sign
        run: |
          xcodebuild \
          -exportArchive \
          -archivePath TestBuildAndSign.xcarchive \
          -exportPath export \
          -exportOptionsPlist options.plist \
          -allowProvisioningUpdates \
          -verbose
