name: Native Build & Test

env:
  cacheId: '4' # increment to expire the cache

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Watch for changes to the `App` and `iOS` paths, use
      # git for cache keys.
      - name: Generate cache key
        run: |
          echo $(git rev-parse HEAD:App) > ./dd-cache-key.txt
          echo $(git rev-parse HEAD:ios) >> ./dd-cache-key.txt

      - name: Cache derived data
        uses: actions/cache@v1
        with:
          path: xbuild/Build
          key: ${{ runner.os }}-dd-xcode-${{ env.cacheId }}-${{ hashFiles('**/dd-cache-key.txt') }}
          restore-keys: |
            ${{ runner.os }}-dd-xcode-${{ env.cacheId }}-

      - name: Build Keychain
        env:
          CERTIFICATE: ${{ secrets.ITUNES_CERT_P12 }}
        run: |
          scripts/makekc.sh ${{ secrets.KEYCHIAN_PASSWD }}

      - name: Build & Sign
        run: |
          xcodebuild \
          -project TestBuildAndSign.xcodeproj \
          -scheme TestBuildAndSign \
          -configuration Release \
          -derivedDataPath xbuild \
          -xcconfig manual.xcconfig \
          -archivePath TestBuildAndSign.xcarchive \
          archive

      - name: Explore 1
        run: |
          ls -lah

      - name: PP
        env:         
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
          PROFILE_ID: 97030e54-555a-4641-b765-c458064c7596
        run: |
          scripts/makepp.sh

      - name: Explore PP
        run: |
          ls -lah ~/MobileDevice/Provisioning\ Profiles/

      - name: Export IPA
        run: |
          xcodebuild \
          -exportArchive \
          -archivePath TestBuildAndSign.xcarchive \
          -exportPath export \
          -exportOptionsPlist options.plist

      - name: Explore 2
        run: |
          ls -lah