name: Native Build & Test

env:
  cacheId: '4' # increment to expire the cache

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # Watch for changes to the `App` and `iOS` paths, use
      # git for cache keys.
      - name: Generate cache key
        run: |
          echo $(git rev-parse HEAD:App) > ./dd-cache-key.txt
          echo $(git rev-parse HEAD:ios) >> ./dd-cache-key.txt

      - name: Cache derived data
        uses: actions/cache@v1
        with:
          path: xbuild/Build
          key: ${{ runner.os }}-dd-xcode-${{ env.cacheId }}-${{ hashFiles('**/dd-cache-key.txt') }}
          restore-keys: |
            ${{ runner.os }}-dd-xcode-${{ env.cacheId }}-

      - name: Foo
        run: |
          scripts/makekc.sh

      - name: Run debug build
        run: |
          xcodebuild \
          -project TestBuildAndSign.xcodeproj \
          -scheme TestBuildAndSign \
          -configuration Debug \
          -derivedDataPath xbuild \
          build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO
