name: Code Quality

env:
  cacheId: '4' # increment to expire the cache

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
      - name: Checkout aries-mobile-agent-react-native
        uses: actions/checkout@v2

      - name: Setup node v12
        uses: actions/setup-node@v2
        with:
          node-version: 12

        # GitHub recommends not caching node_modules but rather
        # .npm because it can break across Node versions and
        #  won't work with npm ci.
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.cacheId }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cacheId }}-

      - name: Install dependencies
        run: |
          npm ci

      - name: Check style
        run: |
          npm run prettier

      - name: LINTing
        run: |
          npm run lint
  test:
    runs-on: ubuntu-18.04
    name: Testing
    steps:
      - name: Checkout aries-mobile-agent-react-native
        uses: actions/checkout@v2

      - name: Setup node v12
        uses: actions/setup-node@v2
        with:
          node-version: 12

        # GitHub recommends not caching node_modules but rather
        # .npm because it can break across Node versions and
        #  won't work with npm ci.
      - name: Cache node modules
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.cacheId }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cacheId }}-

      - name: Install dependencies
        run: |
          npm ci

      - name: Automated testing
        run: |
          npm run test
